name: omass_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - scikit-image
  - pandas
  - pip
  - jupyterlab
  - nodejs
  - scikit-learn
  - jupyter_contrib_nbextensions
  - pip:
      - cookiecutter
      - magicgui
      - napari[all]
