name: omass_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - scikit-image
  - pandas
  - pip
  - jupyterlab
  - nodejs
  - scikit-learn
  - jupyter_contrib_nbextensions
  - nb_conda_kernels
  - pip:
      - cookiecutter
      - magicgui
      - napari[all]
      - sif_parser
      - twine
      - pytest
      - microfilm[all]
  - anaconda:
      - git
