# name: napari-pp-test
name: omass_env_base
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numba
  - pip
  - scikit-image
  - scikit-learn
  - jupyterlab
  - nodejs
  - jupyter_contrib_nbextensions
  - nb_conda_kernels
  - ipykernel
  - pip:
    - napari[all]
    - git+https://github.com/rjlopez2/napari-omaas.git # napari-omaas
    - git+https://github.com/rjlopez2/napari-time_series_plotter.git@custom_use # # install time series plotter from my forked repo
    - git+https://github.com/rjlopez2/napari-mat-file-reader.git
    - git+https://github.com/rjlopez2/napari-sif-reader.git
    - pyqtgraph

    # - microfilm
