# name: napari-pp-test
name: omaas_base_optimap_pip
channels:
  - conda-forge
dependencies:
  - python=3.9
 #  - cupy
  - pip
  - numpy
  - jupyterlab>=3
  - nb_conda_kernels
  - ipykernel
  - nodejs
  - matplotlib
  - ipympl
  - ipywidgets
  - jupyterlab_widgets
  # - m2-base # add this for windows compatibility command shell commands
  - pip:
    # - git+https://github.com/rapidsai/cucim.git@v23.04.01#egg=cucim&subdirectory=python/cucim
    - opticalmapping[all]
    - napari[all]
    # - git+https://github.com/rjlopez2/napari-omaas.git # napari-omaas
    # - git+https://github.com/rjlopez2/napari-time_series_plotter.git@custom_use # # install time series plotter from my forked repo
    # - git+https://github.com/rjlopez2/napari-mat-file-reader.git
    # - git+https://github.com/rjlopez2/napari-sif-reader.git
    # - pyqtgraph
    # - opencv-python-headless

    # - microfilm
