# name: napari-pp-test
name: omass_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pip
  - pandas
  # - matplotlib
  - scikit-image
  - scikit-learn
  - jupyterlab
  - nodejs
  - jupyter_contrib_nbextensions
  - nb_conda_kernels
  - pip:
      - cookiecutter
      - magicgui
      - napari[all]
      - sif_parser
      - twine
      - pytest
      - microfilm[all]
      - napari-svg
      - napari-omaas
      - napari-mat-file-reader
      - mat73 # this works
      - pymatreader
  - anaconda:
      - git
