name: napari-pp-test
# name: omass_env_base
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pip
  - scikit-image
  - scikit-learn
  - jupyterlab
  - nodejs
  - jupyter_contrib_nbextensions
  - nb_conda_kernels
  - pip:
    - napari[all]
    - git+https://github.com/rjlopez2/napari-omaas.git # napari-omaas

    - microfilm
